name = "lunatv"

# Note: For Cloudflare Pages projects, `workers_dev` and `[site]` sections are not
# supported by the Pages configuration. Removing them prevents wrangler validation
# errors like: "Configuration file for Pages projects does not support \"workers_dev\""
# Keep pages_build_output_dir so the Pages build knows where the adapter wrote files.
kv_namespaces = [
  { binding = "LUNATV_KV", id = "0e5a71eeb4ed4028991860be64db207e" }, # TODO: Replace with your KV namespace ID
]

# The output dir produced by next-on-pages / vercel adapter
pages_build_output_dir = ".vercel/output/static"

# Ensure Node.js compatibility flag is set for the produced Worker.
# Putting this in the repository's wrangler.toml makes the setting persistent
# across deployments (UI changes may be overwritten by repo config).
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]
